# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Meissa Docs
email: aangelov@bellatrix.solutions
description: >- # this means to ignore newlines until "baseurl:"
  Here you can find rich documentation about the different features and configurations of Meissa. Also, there is a dedicated section about the research we made and comparison with other available tools.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://docs.meissarunner.com" # the base hostname & protocol for your site, e.g. http://example.com
#twitter_username: jekyllrb
#github_username:  jekyll
permalink: /:title/
#source: jekyll
#destination: documentation 
# Build settings
markdown: kramdown
# theme: minima
plugins:

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
navigation:    
    "what-is-parallel-test-execution":
        title: Parallel Test Execution?
    "advantages-distributed-parallel-test-execution":
        title: Advantages Distributed Testing
    "getting-started":
        title: Getting Started
    "common-challenges":
        title: Parallel Tests Challenges 
    "requirements":
        title: Requirements
    "features":
        title: Features 
    "how-do-we-use-it":
        title: How Do We Use It?    
    "why-did-we-build-it":
        title: Why Did We Build It?
    "history":
        title: History
    "the-biggest-experiment":
        title: The Biggest Experiment
    "when-it-is-appropriate-to-use-and-when-not":
        title: When to Use?
    "how-does-it-work-internally":
        title: How Does It Works?
    "how-to-develop-plugins":
        title: How to Develop Plugins?
    "get-involved":
        title: Get Involved